{{- if .Values.serviceAccount.create }}
{{- $saName := .Values.serviceAccount.name | default (printf "%s-markserv" .Release.Name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    app: {{ .Release.Name }}-markserv
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}
